# Puerto único para el microservicio de Dueños
server.port=8082

# Configuración de la Base de Datos en XAMPP
spring.datasource.url=jdbc:mysql://localhost:3306/db_vetnova_duenos?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# Hibernate (creará la tabla 'duenos' limpia de forma automática)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Nivel de logs para ver los mensajes de SLF4J que agregamos
logging.level.com.vetnova.ms_duenos=INFO